-   id: ml-test
    name: Mircos testing script
    description: This hook echoes foobar.
    entry: ml-test
    language: script
    types: [text]
-   id: ml_lang
    name: Language testing
    stages: [commit-msg]
    description: This hook tests the commit message.
    entry: ml_lang
    language: script
    types: [text]

