#!/bin/bash

# Abfrage, ob Commit-Message (in $1) unsere Sprachvorgaben enthält
case $(egrep -o '^[^: ]+' < "$1") in

        only-de|only-en|content-sync)
                exit
                ;;

        knw|test)
                exit
                ;;

        *)
                echo "Nein, nochmal - Sprachkram fehlt."
                echo "Stattdessen steht am Anfang:"
                echo $(egrep -o '^[^: ]+' < "$1")
                exit 1
                ;;
esac
